### ISSUE TITLE
Specifying new --citeproc option with pandoc 2.11.1.1

### ISSUE THREAD

**Issue by bsag** [joostkremers/pandoc-mode#100]
First, thanks so much for this incredibly useful package!

I've just switched to the latest pandoc (v2.11.1.1). The --filter pandoc-citeproc option is now deprecated, and it is recommended to use --citeproc instead. 

Is it possible to add this option? I tried reverting to using pandoc-citeproc as a filter instead as a workaround, but I get an error:

pandoc-citeproc: Error in $: Incompatible API versions: encoded with [1,22] but attempted to decode with [1,21].

Manually running the command specified by my settings file (minus the filter) but adding the --citeproc option properly processes the references.

Many thanks!

**Comment by joostkremers** [comment]
I've added the option `--citeproc`, let me know if you're running into problems

> pandoc-citeproc: Error in $: Incompatible API versions: encoded with [1,22] but attempted to decode with [1,21].

Honestly, I don't know what this means. If it doesn't resolve itself, asking on the Pandoc mailing list is probably your best option.

**Comment by bsag** [comment]
Wow, thanks for the fast response - it works perfectly!

I was only trying to use the pandoc-citeproc filter as a potential work-around, so now that the --citeproc option is working, I don't need that anyway.

I'll close this issue now. Thanks again for the ultra-speedy update!

**Comment by joostkremers** [comment]
No problem. I've made it so that adding a new Pandoc option requires only a single line of code, so it can be done  fast. :smiley:

I may have missed other new options. I try to keep track, but I sometimes overlook them, so if anything else is missing, do let me know.
