### ISSUE TITLE
Defaults file setting not passed as argument to pandoc command where converting to PDF

### ISSUE THREAD

**Issue by hugoroy** [joostkremers/pandoc-mode#106]
Steps to reproduce:

1. Create a markdown document
2. Create a pandoc defaults settings yaml file
3. Set the yaml file above as defaults file in pandoc-mode
4. Convert the markdown to PDF

The pandoc-mode log shows that the following:

```
==================================================
Thu Aug 19 11:02:19 2021

Calling pandoc with:

pandoc --read=markdown --write=latex --output=/home/hugo/temp//debug-pandoc-mode.pdf

debug-pandoc-mode.md: pandoc finished successfully
```

Expecting a `--defaults=/home/hugo/temp//debug-pandoc-mode.yaml` but it's missing.

Whereas the settings file saved shows that the defaults file setting is well recorded by pandoc-mode:

```
;; -*- mode: emacs-lisp -*-

;; pandoc-mode local settings file for debug-pandoc-mode.md
;; saved on 2021.08.19 11:05

((latexmathml)
[...]
 (defaults . "debug-pandoc-mode.yaml")
[...]
 (master-file))
```

I'm using

 - GNU Emacs 28.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-08-02
 - I'm also using Doom emacs and have installed pandoc-mode through its package system

**Comment by hugoroy** [comment]
The markdown file:

[debug-pandoc-mode.md](https://github.com/joostkremers/pandoc-mode/files/7013172/debug-pandoc-mode.md)

The yaml file (can't be uploaded to GIthub):

```
from: markdown

pdf-engine: xelatex
```

**Comment by joostkremers** [comment]
Thanks for reporting this issue. It turns out that the `defaults` option was completely ignored. This should be fixed now.

**Comment by hugoroy** [comment]
Great :-) I will try
Thanks for fixing and for all the work on pandoc-mode!
