### ISSUE TITLE
pandoc-jump-to-reference not working

### ISSUE THREAD

**Issue by atanasj** [joostkremers/pandoc-mode#107]
I am using `pandoc-mode` with `ebib`. `pandoc-jump-to-reference` no longer words, and I get the error that the citation under point does not work. However, it is in my BibTeX file, which `ebib` can read and find (see image below). 

Can you please help me get to the bottom of why this might be happening, as I'm not too sure where to start… Thanks in advance. 

<img width="579" alt="image" src="https://user-images.githubusercontent.com/27214625/132862903-a66971b0-e624-4b8d-83fe-310b96b66ba9.png">

**Comment by joostkremers** [comment]
Hmm, yes, I get the error too. The bug is caused by a change I made a couple of months back. I pushed a commit that should hopefully fix this.

Thanks for reporting.

**Comment by atanasj** [comment]
Sorted… Thanks!
