### ISSUE TITLE
pandoc-regex-citation-key matches url strings

### ISSUE THREAD

**Issue by sdhoward** [joostkremers/pandoc-mode#121]
I use pandoc-mode when I'm editing markdown, and valid links that contain `@` display improperly.

I dug in a little bit and there's a regex that determines when to use `pandoc-citation-key-face`, which makes the links look wrong.

Surely the regex shouldn't match this string:

<img width="460" alt="Screenshot 2024-09-20 at 11 46 03" src="https://github.com/user-attachments/assets/c7faa5e2-ad44-44bd-a18d-819e6813babe">

**Comment by joostkremers** [comment]
You're right, it's not. But it's not immediately clear how it can be fixed. Seems the only way is to specify that there should not be an alphanumeric character before the @ sign. I'm not sure that that will cover all cases, though. Let's run with it and see whether we get any complaints...

**Comment by sdhoward** [comment]
I've never seen a pandoc citation key in the wild, otherwise I would provide more feedback. The fix you provided (https://github.com/joostkremers/pandoc-mode/commit/ef84876220bdd1504b8c2432a1667d54d640522c) works for me though, thank you.

**Comment by joostkremers** [comment]
Great, thanks for the feedback. I'll close this issue then.
