### ISSUE TITLE
feature request: local variables for default

### ISSUE THREAD

**Issue by fommil** [joostkremers/pandoc-mode#15]
It would be great to be able to specify the default settings for a file using emacs local variables. Do you think that would be possible? And possibly also as an alternative to having lots of settings files.

I'm thinking that it would be most useful for files that only really have one output format. I don't like cluttering up my repositories with dot files, but there is a lot of precedent to have editor-specific strings in comments.

**Comment by lionel-** [comment]
One related problem is that pandoc-mode does not take into account `pandoc-binary` if it's declared as a buffer-local variable. I think it's because `(with-temp-buffer)` does not import local variables of the original buffer.

**Comment by joostkremers** [comment]
For customisable variables, it would be easier to allow buffer-local variants, though as you noticed, this isn't currently implemented. I'll see about implementing it, though I can't promise I'll be able to do it soon.

**Comment by joostkremers** [comment]
I've committed an update that fixes both issues. It is now possible to specify options as file-local variables, using the long form of the option prefixed with `pandoc/`. Furthermore, a file-local settnig for `pandoc-binary` is now treated correctly.

Let me know if you run into any problems with this update.

**Comment by joostkremers** [comment]
BTW, details are discussed in the manual (section "File-local variables").

**Comment by lionel-** [comment]
it works great and it's very useful! Thanks Joost
