### ISSUE TITLE
integration request: mathematics from AucTeX

### ISSUE THREAD

**Issue by fommil** [joostkremers/pandoc-mode#17]
I used to write a lot of LaTeX files and the AucTeX mode was really great for previewing equations. It actually compiles mathematics equations into PNGs and inserts them inline.

Unfortunately, it was designed to work in LaTeX files and that's a baked-in assumption. However, there is no real reason why it (or the principles behind it) should be limited to latex files.

It would be really great to be able to `C-c C-p p` over an equation `$\epsilon$` and see the equation rendered properly... also a mode to auto-parse a file and try to generate all equations.

I doubt emacs' HTML engine is up to using MathJaX.

UPDATE: I just found out that org-mode does this. http://orgmode.org/manual/Previewing-LaTeX-fragments.html#Previewing-LaTeX-fragments

I guess this is really a job for markdown-mode, right?

**Comment by mardukbp** [comment]
(This)[https://github.com/aaptel/preview-latex] might just be what you are looking for. I just tried it in the *scratch* buffer and it works. You can install it with

```lisp
(add-to-list 'package-archives '("MELPA" . "http://melpa.milkbox.net/packages/"))
M-x eval-buffer
M-x package-install RET px RET
```

**Comment by joostkremers** [comment]
Cool stuff. I'll have to look into that.

**Comment by fommil** [comment]
Ix don't know why I didn't close this... org - mode is ideal
