### ISSUE TITLE
Provide syntax highlighting for pandoc extensions

### ISSUE THREAD

**Issue by dfc** [joostkremers/pandoc-mode#2]
It would be nice if some of pandoc's extensions to markdown were fontified. For instance

    Term we will describe/define
     ~ definition / description two 
     ~ definition / description one

and 

    % Title
    % Author
    % Date

**Comment by joostkremers** [comment]
Thanks, that looks great! I added a colon to the citation regexes (I use colon a lot in my citation keys) and merged it into master.
