### ISSUE TITLE
Concept of "master" file?

### ISSUE THREAD

**Issue by hugoroy** [joostkremers/pandoc-mode#21]
[First: I have been using pandoc-mode for a few weeks, and I really like it :-) a lot of things could be improved but it's really useful already! so, thanks!]

Related to #19 (the possibility to "@@include" other input files)

is it possible to set a "master" file? 

IIRC there is such a concept with LaTeX. 

The idea is that we could save this variable in the "Project settings" and thus running pandoc with pandoc-mode on a file, e.g. src/introduction.markdown, would actually provide the content of the "master" file to pandoc, e.g. src/main.markdown which "@@include" introduction.markdown".

That way I don't have to change buffers simply to run pandoc on the main file.

**Comment by joostkremers** [comment]
Yes, AUCTeX has this concept of a master file and I agree it would be nice if `pandoc-mode` had something similar. It shouldn't even be too difficult to implement. I'll see what I can do.

Suggestions for other improvements are always welcome! (And if you know Elisp, code is welcome too, of course. ;-)

**Comment by hugoroy** [comment]
Sorry, my knowledge of lisp is limited to editing pandoc-mode setting files and copy pasting stuff into ".emacs" :-)

**Comment by joostkremers** [comment]
Ok, I've added a master file option. Details are in the manual, section "Master file". See the web page <http://joostkremers.github.io/pandoc-mode/> or the info manual for details on using it.

Let me know if you run into any problems!

**Comment by hugoroy** [comment]
Thanks, it works. A few comments from the user's perspective:

  - I would expect to find this setting in "Pandoc" > "Files" rather than in a new menu of its own.

  - By default, I would set the master  file like a docx/odt "reference" file: as "No Master File" and then let the user set a master file;
 
    otherwise, when the user has the master file in the buffer, the master file is already set to "this file" by default, so if you want to intentionally set the master file setting in the Project setting (so that it applies to all the project's files), you currently have to set the master file to "other  file" and then select the current bufferised file in the filesystem again. 

  - it's a bit surprising that you have to set  the master file's output format; isn't it possible to tell pandoc mode which output  format to use from any of the file in the project? e.g. I have an included file in the buffer, I set the output format to "html5" and so pandoc-mode will look for the project setting for the html5 output, which shuold contain the "'master file" option and  then run pandoc on that master file for the included file's output format.

But that's all polishing, the feature works great :-)

Thanks! that makes me work faster now! ;-) no more switching buffers simply to run pandoc-mode's pandoc

**Comment by joostkremers** [comment]
Thanks for your feedback.

> I would expect to find this setting in "Pandoc" > "Files" rather than in a new menu of its own.

Good point. I moved the menu entry there.

> By default, I would set the master file like a docx/odt "reference" file: as "No Master File" and then let the user set a master file;
> 
> otherwise, when the user has the master file in the buffer, the master file is already set to "this file" by default, so if you want to intentionally set the master file setting in the Project setting (so that it applies to all the project's files), you currently have to set the master file to "other file" and then select the current bufferised file in the filesystem again.

Yes, good point. I changed the names of the menu entries and I added a menu entry “Use This File As Master File”, which also writes a Project settings file

> it's a bit surprising that you have to set the master file's output format; isn't it possible to tell pandoc mode which output format to use from any of the file in the project? e.g. I have an included file in the buffer, I set the output format to "html5" and so pandoc-mode will look for the project setting for the html5 output, which shuold contain the "'master file" option and then run pandoc on that master file for the included file's output format.

Yes (if I understand you correctly), that is how I *intended* it to work. I just forgot to actually implement it that way… Should be fixed now.

For clarity’s sake: the way it should work is that when you run pandoc on an included file, `pandoc-mode` takes the output format from the included file and uses all other options from the master file.

**Comment by hugoroy** [comment]
OK. I will test again!
-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by hugoroy** [comment]
It works fine except for the last part of my feedback: i.e. if I want to change the output format, I need to change the buffer to the main file, change the output format there, and then change buffer again to the include file in order to continue writing in the included file.

**Comment by joostkremers** [comment]
That's strange, because it works fine on my end... Note that you need to set the master file for each output format that you use. If you do that, it should work.

I realise that that's a bit impractical, but it was the quickest way to implement it. `pandoc-mode` doesn't have a way to store settings that apply to a file independent of output format. I’d have to think a bit more about the best way to implement that.

**Comment by hugoroy** [comment]
Yes i think all was set like this. I will try again!
-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by hugoroy** [comment]
It seems to work correctly. I will open other issues if I can produce a specific bug related to this feature.

Thanks a lot
