### ISSUE TITLE
pandoc-citation-extra-face incorrectly defined

### ISSUE THREAD

**Issue by treitmaier** [joostkremers/pandoc-mode#26]
(defvar pandoc-citation-extra-face 'pandoc-citation-marker-face
    "Face name to use for page numbers and other notation.")

should instead be

    (defvar pandoc-citation-extra-face 'pandoc-citation-extra-face
    "Face name to use for page numbers and other notation.")

**Comment by joostkremers** [comment]
Fixed, thanks!
