### ISSUE TITLE
Documentation wrong for default data dir

### ISSUE THREAD

**Issue by dato** [joostkremers/pandoc-mode#30]
As far as I can [see], the default data dir is _~/.emacs.d/pandoc-mode_, but the [documentation] says it’s _~/.emacs.d/pandoc_.

And many thanks for this package, it is immensely useful

[see]: https://github.com/joostkremers/pandoc-mode/blob/ba443a452a38d552b16c6ef23188682437d280dc/pandoc-mode-utils.el#L63
[documentation]: http://joostkremers.github.io/pandoc-mode/#settings-files

**Comment by joostkremers** [comment]
Yes, you're right. Thanks for pointing that out!
