### ISSUE TITLE
Cannot apply defaults when not visiting a file

### ISSUE THREAD

**Issue by dato** [joostkremers/pandoc-mode#32]
I have a default settings file that sets the output format to HTML. It lives in `~/.emacs.d/pandoc-mode/default.pandoc`:

```elisp
((read . "markdown")
 (write . "html")
 (standalone . t))
```
I also have in my init file:

```elisp
(add-hook 'pandoc-mode-hook 'pandoc-load-default-settings)
```

It would be nice if this file would be loaded when creating a new Markdown buffer without an associated file. As in:

```elisp
(defun write-markdown ()
  (switch-to-buffer (generate-new-buffer-name "markdown"))
  (markdown-mode)
  (pandoc-mode))
```

At the moment, I can get what I want by adding a call to:

```elisp
  (pandoc--load-settings-for-file
   (expand-file-name "~/.emacs.d/pandoc/foo.md") "default" t)
```

Thanks for considering!

**Comment by joostkremers** [comment]
This should work now. Let me know if you run into problems.

**Comment by dato** [comment]
It works, thank you!
