### ISSUE TITLE
void variable caddr

### ISSUE THREAD

**Issue by hugoroy** [joostkremers/pandoc-mode#35]
I get an error when launching emacs after updating pandoc-mode:

> Symbol's function definition is void: caddr

Here's what I get with `--debug-init`

Debugger entered--Lisp error: (void-function caddr)
  (caddr hydra)
  (format (caddr hydra) prompt)
  (concat "_" (cadr hydra) "_: " (format (caddr hydra) prompt) (format " [%%s(pandoc--pp-option '%s)]" option))
  (list (concat "_" (cadr hydra) "_: " (format (caddr hydra) prompt) (format " [%%s(pandoc--pp-option '%s)]" option)) (cadr hydra) (intern (concat "pandoc-set-" (symbol-name option))))
  (list (quote quote) (list (concat "_" (cadr hydra) "_: " (format (caddr hydra) prompt) (format " [%%s(pandoc--pp-option '%s)]" option)) (cadr hydra) (intern (concat "pandoc-set-" (symbol-name option)))))
  (list (quote push) (list (quote quote) (list (concat "_" (

**Comment by hugoroy** [comment]
adding (require 'cl) did the trick
https://github.com/joostkremers/pandoc-mode/issues/5

(i'm on a windows machine right now, this may be related)

**Comment by joostkremers** [comment]
Hi, sorry for the late reply. Thanks for reporting this, the `cl` package should simply be `require`d. Not just on Windows. ;-)
