### ISSUE TITLE
Defining new functions and @@directives

### ISSUE THREAD

**Issue by hugoroy** [joostkremers/pandoc-mode#38]
Not so much of an issue with pandoc-mode itself but maybe with the documentation which could be enhanced with a few more examples :-)

I have tried to create an @@directive but failed. My plan was to create a new directive but to make it perform different things depending on the output format chosen.

So for instance, @@test{something} in the markdown input document, and 

- defining a function in the Project.latex.pandoc file to replace `@@test{something}` with `\test{something}`.
- defining a function in the Project.html.pandoc file to replace `@@test{something}` with `<span class="test">something</span>`.

Does that make sense? 

Thanks for your help

**Comment by joostkremers** [comment]
The functions for handling `@@directives` shouldn’t be defined in pandoc-mode settings files, but in your init file (or a file read from your init file). And in your case, you wouldn’t need two functions, one will do. Something like (untested):

```lisp
(defun my-pandoc-test-fun (ofmt &optional text)
  "Handle @@test directives in pandoc-mode."
  (cond
   ((string= ofmt "latex")
    (format "\\test{%s}" text))
   ((string= ofmt "html")
    (format "<span class="test">%s</span>" text))
   (t text)))
```

**Comment by hugoroy** [comment]
Hm. I must be missing something. How do I make pandoc-mode look for my @@test directive? The way it is now, the @@test directive is given as is to pandoc, and thus I get errors such as 

> pandoc-citeproc: reference test not found

**Comment by joostkremers** [comment]
There's a section on defining @@-directives in the manual, which should have all the info. If not, feel free to let me know what parts are unclear, so I can try and improve them.

Basically, you need to define an Elisp function that does the text replacement, and then customise `pandoc-directives` so that your directives is recognised.

**Comment by hugoroy** [comment]
Okay. I'll suggest a modification of the documentation, I forgot to change the variables to tell which @@directive is using which function. :-)
