### ISSUE TITLE
pandoc-convert-to-pdf does not work for beamer

### ISSUE THREAD

**Issue by mardukbp** [joostkremers/pandoc-mode#40]
When the output format is beamer, pandoc is called with:

 `pandoc --read=markdown --output=slideshow.pdf`

which results in a LaTeX compilation error. It should be called instead with:

 `pandoc --read=markdown -t beamer --output=slideshow.pdf`

**Comment by joostkremers** [comment]
See if commit e55df4e fixes it.

**Comment by mardukbp** [comment]
Thank you!
