### ISSUE TITLE
Error when starting emacs

### ISSUE THREAD

**Issue by mardukbp** [joostkremers/pandoc-mode#41]
I updated pandoc-mode with `el-get` and now I am getting an error when starting emacs with `emacs --daemon`:

```
Loading /home/marduk/.emacs.d/el-get/pandoc-mode/pandoc-mode.el (source)...
Eager macro-expansion failure: (range-error "ceiling" 1.0e+INF)
```

However, when starting emacs with `emacs --debug-init` the error does not show up. The `ceiling` function is called by a function in `pandoc-mode-utils`.

**Comment by joostkremers** [comment]
The error occurs during (eager) macro expansion, so it doesn’t happen while loading `pandoc-mode-utils.el`. I suspect the problem occurs when `pandoc-mode.el` is loaded, specifically when the hydras are defined. But I’ll need to look into it more thoroughly to figure out what’s going on.

Do you get that error once or twice? Does it still happen when `pandoc-mode.el` is byte-compiled? (The message says it’s loading the source.)

**Comment by mardukbp** [comment]
I just installed pandoc-mode 20150601.1303 from melpa and the error is gone.

**Comment by joostkremers** [comment]
Good! Thanks for letting me know!
