### ISSUE TITLE
Citation regex not recognizing in-text citation at beginning of file

### ISSUE THREAD

**Issue by treitmaier** [joostkremers/pandoc-mode#45]
If I start a document with an in-text citation, then the regex you use to identify that citation and give it a different font face does not work.

For instance, the citation in the following example does not get picked up:

    ==Begin File
    @Einstein1904 discovered the theory ...
    ==End File

whereas in this example the citation gets recognized:

    ==Begin File
    Albert @Einstein1904 discovered the theory ...
    ==End File

**Comment by joostkremers** [comment]
Mmm, yes, I notice it too. Something wrong with the regexp identifying in-text citations. I'll have a look at it.
