### ISSUE TITLE
Underscores in Tex math treated as emphasis

### ISSUE THREAD

**Issue by NickRSearcy** [joostkremers/pandoc-mode#51]
Here is an example of the behavior

<img width="361" alt="screen shot 2015-08-04 at 1 11 26 am" src="https://cloud.githubusercontent.com/assets/1048977/9053651/c7ffa086-3a45-11e5-9cb4-a962d75db158.png">

**Comment by joostkremers** [comment]
Actually, this is an issue with `markdown-mode`, not with `pandoc-mode`, so I can't really do much about it...
