### ISSUE TITLE
Passing custom options to pandoc from the menu

### ISSUE THREAD

**Issue by japhir** [joostkremers/pandoc-mode#54]
Hi there!

This might be me, who hasn't figured out the weird directives correctly yet, but I'd like to be able to pass extra arguments to pandoc from the hydra menu. Because right now I need to create a separate makefile with the correct options, meaning I have to go to the command line, cd to the directory and run the file in stead of C-c / r. 

The option I want to pass is --filter=pandoc-fignos (to implement figure numbering in the way that will probably be added to pandoc in the future, see [pandoc fignos on github](https://github.com/tomduck/pandoc-fignos)).

Is this already possible and am I missing something or is this currently not possible?

Kind regards

**Comment by joostkremers** [comment]
Filters can be specified in the reader options submenu (`C-/ o r`).

I don't use filters myself, so I've never actually tested this functionality very thoroughly. If it does not work as advertised, please let me know so I can fix it.

**Comment by japhir** [comment]
Awesome, it works even though the option asks for a file in stead of a
string. But when passing "pandoc-fignos" as an argument it does work.

**Comment by joostkremers** [comment]
Hmm, perhaps I should change the type of that option from `file` to `string`, since Pandoc expects a filter to be the name of an executable and searches for it in $PATH. If a user wants to specify a file path, that would still be possible, there just wouldn't be any file name completion.

**Comment by japhir** [comment]
I'm not sure, this was also the first time I used a filter and I don't know if people usually install them and just pass the string-argument or put them in a folder and pass the location argument.

**Comment by joostkremers** [comment]
I've made some changes to the way file options are handled that should improve this situation. Now, file options are stored as relative file paths and not expanded. Setting a filter should now be easier.
