### ISSUE TITLE
@@-directives in included files do not get processed

### ISSUE THREAD

**Issue by anghyflawn** [joostkremers/pandoc-mode#56]
Says it all really: I have a number of custom `@@`directives that are processed fine when the file is compiled as a standalone, but when the same file is `@@include`d in another one I get (**???**) in the output (similar to unresolved references). I'm guessing this is because `pandoc-process-directives` only gets run once?

**Comment by joostkremers** [comment]
`pandoc-process-directives` processes the directives in the order in which they appear in `pandoc-directives`, so I assume that your custom directives appear before the include directive.

It's not very intuitive that way, I have to admit, so I just pushed an update that should fix it. With the fix, `@@`-directives in included files should be processed regardless of the order in which they appear in `pandoc-directives`.

Let me know if you run into any trouble with the update.

**Comment by anghyflawn** [comment]
Thanks! This works. Yes, I'm adding things to `pandoc-directives` with `add-to-list` rather than through Customize, so that must be the reason.

**Comment by joostkremers** [comment]
Yes, `add-to-list` adds stuff to the front of a list, so that explains it. There's no reason, though, why that should lead to problems.

Interestingly, the code is simpler now than it was before (not much, but a little)...
