### ISSUE TITLE
Unsetting css or bibliography

### ISSUE THREAD

**Issue by lionel-** [joostkremers/pandoc-mode#57]
Hello,

Apparently there is no easy way to unset some types of options. E.g. `css` or `bibliography`.

When I do
```lisp
(pandoc--set 'css "some.css")
(pandoc--set 'css "other.css")
(pandoc--set 'css nil)
```
the `css` option is set to `(css nil "other.css" "some.css")` instead of being unset.

**Comment by joostkremers** [comment]
Yes, those are list options, which means items can only be removed one at a time (with `pandoc--remove-from-list-option` or with `C-u - M-x pandoc-set-css`). But I guess it shouldn't be too difficult to add a way to unset it completely in one go.

If I may ask, though, for what reason are you using `pandoc--set` directly?

**Comment by lionel-** [comment]
Thanks, I didn't know about that command.

> If I may ask, though, for what reason are you using pandoc--set directly?

I'm programmatically setting and unsetting options. Is there a better way to do it?

**Comment by joostkremers** [comment]
> I'm programmatically setting and unsetting options. Is there a better way to do it?

I guess that depends on what your goal is. I'd need to know a bit more about how exactly you're setting and unsetting options. (Setting options programmatically is not a use-case I ever envisaged. Perhaps I can add some functionality to `pandoc-mode` to make it easier.)

Regardless, however, I agree that it makes sense that `(pandoc--set 'css nil)` should unset the option, not add `nil` to the list, so I'll change that. That should at least solve your issue.

**Comment by lionel-** [comment]
Well for a given file I need to be able to switch between different kinds of output (pdf, docx, html), each with their own settings. I use the same output settings all the time so I have a function that applies them as a function of the desired output type. I have that function in the file-local variables.

Besides, I'm not a fan of the dotted files the hydra commands create :/ They clutter the project folders and show up in helm. I understand this may be a handy approach for many people though.

>  I agree that it makes sense that (pandoc--set 'css nil) should unset the option, not add nil to the list, so I'll change that

Thanks!

**Comment by joostkremers** [comment]
> Well for a given file I need to be able to switch between different kinds of output (pdf, docx, html), each with their own settings. I use the same output settings all the time so I have a function that applies them as a function of the desired output type. I have that function in the file-local variables.

Ah, I see. That possibility had never occurred to me. :-)

An alternative if you always have the same settings for a particular output format is to use a global settings file. If `pandoc-mode` doesn't find a local or a project settings file in the current directory, it looks for a global settings file in `~/.emacs.d/pandoc-mode/` (which can be customised).

But there's nothing wrong with your method, of course. Though I guess it would be better to make `pandoc--set` a user-accessible function and add a note to the manual, so that I'll know not to change it on a whim.

> Besides, I'm not a fan of the dotted files the hydra commands create :/ They clutter the project folders and show up in helm. I understand this may be a handy approach for many people though.

I must admit I'm not a big fan of them either. I've been considering the idea of using a single settings file that contains settings for all output formats, which would at least be less clutter.

> > I agree that it makes sense that (pandoc--set 'css nil) should unset the option, not add nil to the list, so I'll change that
> Thanks!

Done. Let me know if you run into trouble, though.

**Comment by lionel-** [comment]
> I must admit I'm not a big fan of them either. I've been considering the idea of using a single settings file that contains settings for all output formats

A compromise might be to set a custom folder in ~/.emacs.d/ where dotted files would be stored. Many Emacs packages use that approach.

> Done. Let me know if you run into trouble, though

Thanks!

**Comment by joostkremers** [comment]
> A compromise might be to set a custom folder in ~/.emacs.d/ where dotted files would be stored. Many Emacs packages use that approach.

Like i said, `pandoc-mode` already uses this option to store global settings files. Also, using it for settings files from different directories would require some non-trivial effort to make sure files with identical names but different paths do not conflict.

**Comment by lionel-** [comment]
> would require some non-trivial effort to make sure files with identical names but different paths do not conflict.

Just FYI, you can probably reuse (parts of) `(make-backup-file-name-1)` in files.el.

**Comment by joostkremers** [comment]
> Just FYI, you can probably reuse (parts of) (make-backup-file-name-1) in files.el.

Yes, I was looking at that code too. Might do something like that.
