### ISSUE TITLE
Missing parenthesis, package uninstallable

### ISSUE THREAD

**Issue by plantarum** [joostkremers/pandoc-mode#60]
Hi,

You're missing a closing parenthesis for the function pandoc-set-file-scope:

https://github.com/joostkremers/pandoc-mode/blob/master/pandoc-mode.el#L845

Installing the package fails with "forward-sexp: Scan error: "Unbalanced parentheses", 38862, 60536"

Thanks

**Comment by joostkremers** [comment]
Sorry about that. Should be fixed now. Thanks for reporting!
