### ISSUE TITLE
Compatibility with Pandoc version 2.0

### ISSUE THREAD

**Issue by MasWag** [joostkremers/pandoc-mode#72]
In pandoc 2.0, `--latex-engine` and `--latex-engine-opt` changed to `--pdf-engine` and `--pdf-engine-opt`. So we cannot specify these options. If we specify these options, pandoc returns error. The same problem is also reported in https://github.com/shd101wyy/markdown-preview-enhanced/issues/665.

**Comment by joostkremers** [comment]
As an initial step toward supporting Pandoc 2, I've pushed a commit that adds the new options. That should at least take care of the immediate incompatibilities.

Do let me know if you run into any further problems.

**Comment by ad2h** [comment]
Looks like also `--reference-docx` and `--reference-odt` are affected by this. Both were replaced by `--reference-doc`, which makes using a reference file impossible. The output is:

> --reference-odt has been removed. Use --reference-doc instead.
> Try pandoc --help for more information.

(or -docx accordingly)

**Comment by joostkremers** [comment]
The relevant option is called `"Style Reference Document"` in the `pandoc-mode` menu. Perhaps I should simply call it `"Reference Doc"`...

**Comment by joostkremers** [comment]
Done: 883e131c53a6351a239c422f05027aa526181ddb.

**Comment by ivan-m** [comment]
`--parse-raw` is no longer valid (need to use `+raw_html` or `+raw_tex` instead).

Not sure when it was removed (as it's not in the changelog), but `--smart` has also been removed (and should be replaced with `+smart`).

**Comment by joostkremers** [comment]
`+raw_html` and `raw_tex` are already among the extensions, so they shouldn't pose a problem. `+smart` isn't, but I just pushed a fix: ba5908ed13a480d12b1a7b258332813fe3e3f94f.

I'm not removing the old options, because people may still depend on older versions of Pandoc.

There's more that needs to be done to make `pandoc-mode` fully compatible with Pandoc 2, but hopefully that will do for the moment. Do let me know if there are other issues.

**Comment by pmwisse** [comment]
The 'smart' option does no longer work either. I get this message: 

--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.

**Comment by joostkremers** [comment]
Uncheck the `smart` option in the menu and check the `smart` extension. `pandoc-mode` offers both, because some users may still be using older versions of Pandoc. You should choose the one that works on your Pandoc.

**Comment by pmwisse** [comment]
I see, thanks and apologies for not sorting this out for myself.

Op di 19 mrt. 2019 12:32 schreef Joost Kremers <notifications@github.com>:
