### ISSUE TITLE
Citations haven't been appended

### ISSUE THREAD

**Issue by allenryb** [joostkremers/pandoc-mode#77]
I am a new guy of emacs, markdown-mode and pandoc-mode.

My problem is that references haven't been appended after I hit `C-c / p`.

By Pandoc Help,  my option is 

> ((bibliography "myref.bib")
 (natbib . t)
 (biblatex . t)
 (read . "markdown_github")
 (write . "native"))

But the log is 

> Calling pandoc with:
pandoc --read=markdown_github --write=latex --output=c:/Users/allenryb/Desktop/aa//aa.pdf
aa.md: pandoc finished successfully

So **pandoc hasn't called bibliography**.
In my Terminal, I use 

>  pandoc aa.md --bibliography myref.bib -o aa.pdf

Everything is OK. I want to ask what should I do to make pandoc call bibliography?

Thanks in advance!

**Comment by joostkremers** [comment]
You'll need to tell `pandoc-mode` which options to pass to `pandoc`. `C-c / o` gets you to the options menu, you can take it from there. Note that you should always set the output format first (`C-c / O`), because the options you set only apply to the current output format.

**Comment by allenryb** [comment]
Thanks very much @joostkremers ! Follow your answer, I have fixed my problem.
