### ISSUE TITLE
Unknown writer: powerpoint

### ISSUE THREAD

**Issue by newhallroad** [joostkremers/pandoc-mode#78]
Thank you for an amazing tool and for the most recent update.

I am using pandoc 2.1 and pandoc-mode-20180506.1713.

When I try to convert markdown to pptx with pandoc-mode, I get the message `Unknown writer: powerpoint`. Using the command line to convert to pptx succeeds.

Many thanks for your advice on fixing this.

**Comment by joostkremers** [comment]
That was clearly a bug. I used `"powerpoint"` as the output format for Powerpoint slides, but Pandoc actually uses `pptx`. Should be fixed in the latest commit.

Thanks for reporting!

**Comment by newhallroad** [comment]
Makes sense. Thanks for the very quick response. And thanks again for the fantastic tool.
