### ISSUE TITLE
Input format selection sets output format

### ISSUE THREAD

**Issue by abradd** [joostkremers/pandoc-mode#83]
I'm running pandoc-mode version 20180710.1446 from Melpa. 

When setting the input format to anything it seems to set the output format to that selection instead and the input format is unaffected.

**Comment by joostkremers** [comment]
Yup, you're right. That's an actual bug. I'm pushing a fix for this.

Thanks for pointing this out.

**Comment by joostkremers** [comment]
Do let me know if you run into further trouble.

**Comment by abradd** [comment]
Looks like this issue was corrected. I tested in 20180727.2201 from Melpa. Cheers.
