### ISSUE TITLE
Changed settings for output format cannot be saved.

### ISSUE THREAD

**Issue by abradd** [joostkremers/pandoc-mode#84]
Using 20180727.2201 for Melpa. When updating the output format I am prompted to save the current settings for original output format (not the one I am changing to). If I select yes, an error is produced with `Wrong type argument: stringp, nil`

Steps to reproduce:
1. Enter pandoc-mode with C-c /
2. Set output format
3. Set or change input format
4. Change output format
The prompt will occur at this point.

**Comment by joostkremers** [comment]
This doesn't happen on my machine, so I'm afraid I'll need to ask you if you could do some debugging. Could you, after setting the output format in step 2, check the `pandoc-mode` settings with `C-/ S`?

It would probably also help if you could run the uncompiled source (move the `*.elc` files for `pandoc-mode` out of the way and restart Emacs) and do `M-x toggle-debug-on-error` before triggering the error. Thanks.

**Comment by abradd** [comment]
I'll try to do some debugging in the next few days and get back to you. Cheers.

**Comment by joostkremers** [comment]
Have you made any progress on this?

**Comment by abradd** [comment]
Haven't figured it out yet, but I'm pretty confident this isn't related to pandoc-mode as I am seeing the behaviour in some other circumstances. I'll close this and get back to you if it turns out that is it related to pandoc-mode.

Cheers

**Comment by joostkremers** [comment]
Still, feel free to send me a backtrace of the error. Perhaps I can glean something from it.
