### ISSUE TITLE
Feature request: Option to force specific filters

### ISSUE THREAD

**Issue by Cerebus** [joostkremers/pandoc-mode#89]
I'd like the ability to tell pandoc-mode to run pandoc with specific `--filters` even when they wouldn't normally be triggered.

My specific use case:  I prefer to define `bibliography` in a metadata file, but since pandoc-mode doesn't parse the metadata file it doesn't know to add `--filter pandoc-citeproc` to the shell command.  An override would let me force citeproc while only setting the metadata file in the pandoc-mode settings file.

**Comment by joostkremers** [comment]
Doesn't it suffice to set the filter in the pandoc-mode settings file? I'm not sure what other way to "force specific filters" you have in mind...

**Comment by Cerebus** [comment]
D'oh!  I completely missed that in reader options.
