### ISSUE TITLE
Deprecated CLI call: markdown_github should be gfm

### ISSUE THREAD

**Issue by equwal** [joostkremers/pandoc-mode#90]
The following error is coming up when I am converting from Org mode to Github markdown
```
[WARNING] Deprecated: markdown_github. Use gfm instead.

```
I am using pandoc 2.2.1.

**Comment by joostkremers** [comment]
`pandoc-mode` has both `markdown_github` and `gfm` as in- and output formats, so you can select the correct one. Since Pandoc itself still supports both variants, I'm not going to change this. (Though perhaps I should mark it as obsolete.)

**Comment by joostkremers** [comment]
> (Though perhaps I should mark it as obsolete.)

Ok, just did: 7fe60daa282dc3ffd53a4888ff83e27de8265a65.
