### ISSUE TITLE
Convert and Open

### ISSUE THREAD

**Issue by TshuW** [joostkremers/pandoc-mode#92]
Is there any possible to add function convert and open output file?

**Comment by joostkremers** [comment]
Yes, that's long been a wish of mine as well. Perhaps I'll find some time in the coming weeks to work on this.

**Comment by joostkremers** [comment]
The most recent changes, which I just pushed to Github, now provide this functionality. To be precise, there is a function `pandoc-view-output`, that tries to display the file created by the most recent call to `pandoc`. If you want this file to be opened automatically, you can add this function to `pandoc-async-success-hook`.

I haven't tested this much yet, so if you run into any problems, I'd appreciate it if you'd let me know. Also, if you feel that the  functionality can be improved in some way, feel free to make suggestions.

**Comment by TshuW** [comment]
I'll try it later, thx a lot!
