### ISSUE TITLE
Pandoc viewer not available in menu

### ISSUE THREAD

**Issue by y2klol** [joostkremers/pandoc-mode#98]
In the documentation this line exists:
After running Pandoc, you can view the output file with the option View output file in the menu (or C-c / v). Emacs will try to display the file created during the most recent Pandoc run. 

When I run C-c / I get this menu 
![Screenshot_20200716_013629](https://user-images.githubusercontent.com/7161748/87565364-e2f93180-c704-11ea-9203-d0a96d9c7c32.png)

there is no "View output file" option. "view output buffer" just presents a empty frame.

**Comment by joostkremers** [comment]
Sorry, I somehow missed your post. The screen shot suggests you have an older version of pandoc-mode installed. The latest version does have the menu item you mention.

**Comment by y2klol** [comment]
Solved by updating to the latest version.
