### ISSUE TITLE
How to turn on pandoc extension?

### ISSUE THREAD

**Issue by pearlzli** [joostkremers/pandoc-mode#99]
I'd like pandoc to parse task lists, e.g.

```
- [ ] This task is incomplete
- [x] This task is complete
```

At the moment, when I run pandoc (Markdown to HTML) from pandoc-mode, these just get parsed as text, rather than turned into checkboxes. My understanding is that this requires the task_lists pandoc extension. Is there a way to turn this on in pandoc-mode? I wasn't able to find it in the options menu, nor did I see a way to do it using `customize-group` - though I did see settings for "pandoc extension active/inactive marker".

My apologies if this is something documented somewhere that I've just missed... Thanks!

**Comment by joostkremers** [comment]
In the `pandoc-mode` menu (hydra), when you select `O: Output format`, there should be an option `X: Extensions` at the bottom. That should give you a list of extensions, with the ones that are active checked. You can toggle an extension by typing its number and then pressing `t`.

HTH

**Comment by pearlzli** [comment]
I think my eyes completely skipped over that in the menu. Thanks so much for the quick response!

**Comment by joostkremers** [comment]
You're welcome. Glad I could help. :-)
